pages:
  - name: ホーム - 未来
    path: /2023-03-04
  - name: ホーム - 現在
    path: /
  - name: ホーム - 過去
    path: /2023-02-28
  - name: 出走表
    path: /races/69038403-5e53-4791-8dba-1fc412180c54/race-card
  - name: オッズ - 締め切り前
    path: /races/300d18a3-b115-452f-891e-61eba54f229e/odds
  - name: オッズ - 締め切り後
    path: /races/69a98b63-84c4-422c-8a65-fe1f66baf656/odds
  - name: 結果
    path: /races/d0482b1b-cb79-48dc-903c-5d9edbf7c49b/result
viewports:
  - name: Pixel 5
    width: 393
    height: 851
  - name: Kindle Fire HDX
    width: 800
    height: 1280
  - name: Desktop
    width: 1280
    height: 720
